### ISSUE TITLE
How can I compile it and flash it to the phone?

### ISSUE THREAD

**Issue by hamjin** [Tkpointz/android_kernel_aresin#2]
For Redmi does not update their document about compiling kernel and flash it on recent  device, could you write a wiki about how to compile it and flash it to the phone? Thank you very much.

**Comment by ruje0504** [comment]
https://zixijian.github.io/2021/01/15/008.html

I only have Chinese version.
What the tutorial doesn't say is that CPIO and DTC should be replaced with arm version.

**Comment by hamjin** [comment]
Compile Succeed
