### ISSUE TITLE
bootloop   why?

### ISSUE THREAD

**Issue by ImKK666** [Tkpointz/android_kernel_aresin#4]
Phone Model:Redmi K40 Gaming (Mainland China version)
System Version:MIUI 14.0.3
Processor:MTK D1200

Compiler tool:https://github.com/ZyCromerZ/Clang

Here is my compilation script.
```shell
#!/bin/bash
###########################
#  a kernel build script
###########################

##
#  some color setting
##
cinfo="\x1b[38;2;79;155;250m"
cwarn="\x1b[38;2;255;200;97m"
cerror="\x1b[38;2;240;96;96m"
cno="\x1b[0"


echo -e "${cinfo}=============== Setup Some Export ===============${cno}"
# 内核工作目录
export KERNEL_DIR=$(pwd)
# 内核 defconfig 文件
export KERNEL_DEFCONFIG=aresin_defconfig
# 编译临时目录，避免污染根目录
export OUT=out
# clang 绝对路径
export CLANG_PATH=/root/k40g/toolchain/zyc-clang
export PATH=${CLANG_PATH}/bin:${PATH}
export CLANG_TRIPLE=aarch64-linux-gnu-
# arch平台，这里时arm64
export ARCH=arm64
export SUBARCH=arm64
# 只使用clang编译需要配置
export LLVM=1
export BUILD_INITRAMFS=1

# 编译时线程指定，默认单线程，可以通过参数指定，比如4线程编译
# ./build.sh 4 
TH_COUNT=32
if [[ "" != "$1" ]]; then
        TH_NUM=$1
fi

# 编译参数
export DEF_ARGS="O=${OUT} \
                                CC=clang \
                                CXX=clang++ \
                                ARCH=${ARCH} \
                                CROSS_COMPILE=${CLANG_PATH}/bin/aarch64-linux-gnu- \
                                CROSS_COMPILE_ARM32=${CLANG_PATH}/bin/arm-linux-gnueabi- \
                                LD=ld.lld "
export BUILD_ARGS="-j${TH_COUNT} ${DEF_ARGS}"

echo -e "${cwarn}kernel workspace dir is => ${KERNEL_DIR}"
echo -e "kernel build defonfig is => ${KERNEL_DEFCONFIG}"
echo -e "build tmpdir is => ${KERNEL_DIR}/${OUT}"
echo -e "clang path is => ${CLANG_PATH}"
echo -e "build arch/subarch is => ${ARCH} / ${SUBARCH}${cno}"
# 等待10s，查看配置文件信息是否正确，不正确 Ctrl + C 及时取消
sleep 10s

echo -e "${cinfo}=============== Make defconfig ===============${cno}"
# make defconfig
make ${DEF_ARGS} ${KERNEL_DEFCONFIG}
# 如果命令没有出错，继续执行，否则退出编译
if [[ "0" != "$?" ]]; then
        echo -e "${cerror}>>> make defconfig error, build stop!${cno}"
        exit 1
fi

echo -e "${cinfo}=============== Make Kernel  ===============${cno}"
make ${BUILD_ARGS}
if [[ "0" != "$?" ]]; then
        echo -e "${cerror}>>> build kernel error, build stop!${cno}"
        exit 1
fi
echo -e "${cwarn}>>> build kernel success${cno}"
exit 0

```

The compilation passed successfully.

Extract the boot.img of MIUI 14.0.3 wirebrush package
Unpack it by unpacking tool (https://github.com/xiaoxindada/magiskboot_ndk_on_linux)
![image](https://github.com/Tkpointz/android_kernel_aresin/assets/100894732/2fb8f3cb-4149-4efd-aeb9-0b73e4b89dd5)

Delete the unpacked kernel
![image](https://github.com/Tkpointz/android_kernel_aresin/assets/100894732/0ccee865-2934-43e1-8c6f-06c64efcd3ce)

Replace the kernel with the compiled Image (Image:out/arch/arm64/boot/Image)
![image](https://github.com/Tkpointz/android_kernel_aresin/assets/100894732/f42f23b3-9fcd-4e70-827b-8efb9f47b323)
![image](https://github.com/Tkpointz/android_kernel_aresin/assets/100894732/89705467-9e7e-451c-a06a-c877b7f4dd14)

Finally, package it back

Enter fastboot
Refresh process 

![image](https://github.com/Tkpointz/android_kernel_aresin/assets/100894732/926df72b-d6b0-43eb-84f5-8cca42a09a7d)

Result bootloop

(Directly flashed into the extracted original boot.img, can boot up smoothly)

**Comment by meiranzheng** [comment]
这个内核代码只适用于A11,或许你应该尝试https://github.com/anotherjin/android_kernel_xiaomi_ares
虽然这个是适用于A12,A13的miui,但可能会有很多问题。
最好的解决方法是降级到A11

**Comment by ImKK666** [comment]
> 这个内核代码只适用于A11,或许你应该尝试https://github.com/anotherjin/android_kernel_xiaomi_ares 虽然这个是适用于A12,A13的miui,但可能会有很多问题。 最好的解决方法是降级到A11


A13 bug 太恐怖了 C口驱动有问题  不能充电 不能识别USB, 麦克风驱动也有问题 无法收音,偶尔还会 花屏一下

**Comment by Tkpointz** [comment]
> Phone Model:Redmi K40 Gaming (Mainland China version) System Version:MIUI 14.0.3 Processor:MTK D1200
> 
> Compiler tool:https://github.com/ZyCromerZ/Clang
> 
> Here is my compilation script.
> 
> ```shell
> #!/bin/bash
> ###########################
> #  a kernel build script
> ###########################
> 
> ##
> #  some color setting
> ##
> cinfo="\x1b[38;2;79;155;250m"
> cwarn="\x1b[38;2;255;200;97m"
> cerror="\x1b[38;2;240;96;96m"
> cno="\x1b[0"
> 
> 
> echo -e "${cinfo}=============== Setup Some Export ===============${cno}"
> # 内核工作目录
> export KERNEL_DIR=$(pwd)
> # 内核 defconfig 文件
> export KERNEL_DEFCONFIG=aresin_defconfig
> # 编译临时目录，避免污染根目录
> export OUT=out
> # clang 绝对路径
> export CLANG_PATH=/root/k40g/toolchain/zyc-clang
> export PATH=${CLANG_PATH}/bin:${PATH}
> export CLANG_TRIPLE=aarch64-linux-gnu-
> # arch平台，这里时arm64
> export ARCH=arm64
> export SUBARCH=arm64
> # 只使用clang编译需要配置
> export LLVM=1
> export BUILD_INITRAMFS=1
> 
> # 编译时线程指定，默认单线程，可以通过参数指定，比如4线程编译
> # ./build.sh 4 
> TH_COUNT=32
> if [[ "" != "$1" ]]; then
>         TH_NUM=$1
> fi
> 
> # 编译参数
> export DEF_ARGS="O=${OUT} \
>                                 CC=clang \
>                                 CXX=clang++ \
>                                 ARCH=${ARCH} \
>                                 CROSS_COMPILE=${CLANG_PATH}/bin/aarch64-linux-gnu- \
>                                 CROSS_COMPILE_ARM32=${CLANG_PATH}/bin/arm-linux-gnueabi- \
>                                 LD=ld.lld "
> export BUILD_ARGS="-j${TH_COUNT} ${DEF_ARGS}"
> 
> echo -e "${cwarn}kernel workspace dir is => ${KERNEL_DIR}"
> echo -e "kernel build defonfig is => ${KERNEL_DEFCONFIG}"
> echo -e "build tmpdir is => ${KERNEL_DIR}/${OUT}"
> echo -e "clang path is => ${CLANG_PATH}"
> echo -e "build arch/subarch is => ${ARCH} / ${SUBARCH}${cno}"
> # 等待10s，查看配置文件信息是否正确，不正确 Ctrl + C 及时取消
> sleep 10s
> 
> echo -e "${cinfo}=============== Make defconfig ===============${cno}"
> # make defconfig
> make ${DEF_ARGS} ${KERNEL_DEFCONFIG}
> # 如果命令没有出错，继续执行，否则退出编译
> if [[ "0" != "$?" ]]; then
>         echo -e "${cerror}>>> make defconfig error, build stop!${cno}"
>         exit 1
> fi
> 
> echo -e "${cinfo}=============== Make Kernel  ===============${cno}"
> make ${BUILD_ARGS}
> if [[ "0" != "$?" ]]; then
>         echo -e "${cerror}>>> build kernel error, build stop!${cno}"
>         exit 1
> fi
> echo -e "${cwarn}>>> build kernel success${cno}"
> exit 0
> ```
> 
> The compilation passed successfully.
> 
> Extract the boot.img of MIUI 14.0.3 wirebrush package Unpack it by unpacking tool (https://github.com/xiaoxindada/magiskboot_ndk_on_linux) ![image](https://user-images.githubusercontent.com/100894732/246603968-2fb8f3cb-4149-4efd-aeb9-0b73e4b89dd5.png)
> 
> Delete the unpacked kernel ![image](https://user-images.githubusercontent.com/100894732/246603979-0ccee865-2934-43e1-8c6f-06c64efcd3ce.png)
> 
> Replace the kernel with the compiled Image (Image:out/arch/arm64/boot/Image) ![image](https://user-images.githubusercontent.com/100894732/246603990-f42f23b3-9fcd-4e70-827b-8efb9f47b323.png) ![image](https://user-images.githubusercontent.com/100894732/246604002-89705467-9e7e-451c-a06a-c877b7f4dd14.png)
> 
> Finally, package it back
> 
> Enter fastboot Refresh process
> 
> ![image](https://user-images.githubusercontent.com/100894732/246603931-926df72b-d6b0-43eb-84f5-8cca42a09a7d.png)
> 
> Result bootloop
> 
> (Directly flashed into the extracted original boot.img, can boot up smoothly)

this kernel source is based on Android 11, used for building aosp rom

**Comment by ImKK666** [comment]
> this kernel source is based on Android 11, used for building aosp rom

Yes, I have flashed MIUI 12.5.12.0.
Now my phone is on Android 11.
And it's successfully flashed and booted.

But the USB doesn't work, it doesn't charge, it doesn't connect to the PC.

xD

**Comment by ImKK666** [comment]
> > Phone Model:Redmi K40 Gaming (Mainland China version) System Version:MIUI 14.0.3 Processor:MTK D1200
> > Compiler tool:https://github.com/ZyCromerZ/Clang
> > Here is my compilation script.
> > ```shell
> > #!/bin/bash
> > ###########################
> > #  a kernel build script
> > ###########################
> > 
> > ##
> > #  some color setting
> > ##
> > cinfo="\x1b[38;2;79;155;250m"
> > cwarn="\x1b[38;2;255;200;97m"
> > cerror="\x1b[38;2;240;96;96m"
> > cno="\x1b[0"
> > 
> > 
> > echo -e "${cinfo}=============== Setup Some Export ===============${cno}"
> > # 内核工作目录
> > export KERNEL_DIR=$(pwd)
> > # 内核 defconfig 文件
> > export KERNEL_DEFCONFIG=aresin_defconfig
> > # 编译临时目录，避免污染根目录
> > export OUT=out
> > # clang 绝对路径
> > export CLANG_PATH=/root/k40g/toolchain/zyc-clang
> > export PATH=${CLANG_PATH}/bin:${PATH}
> > export CLANG_TRIPLE=aarch64-linux-gnu-
> > # arch平台，这里时arm64
> > export ARCH=arm64
> > export SUBARCH=arm64
> > # 只使用clang编译需要配置
> > export LLVM=1
> > export BUILD_INITRAMFS=1
> > 
> > # 编译时线程指定，默认单线程，可以通过参数指定，比如4线程编译
> > # ./build.sh 4 
> > TH_COUNT=32
> > if [[ "" != "$1" ]]; then
> >         TH_NUM=$1
> > fi
> > 
> > # 编译参数
> > export DEF_ARGS="O=${OUT} \
> >                                 CC=clang \
> >                                 CXX=clang++ \
> >                                 ARCH=${ARCH} \
> >                                 CROSS_COMPILE=${CLANG_PATH}/bin/aarch64-linux-gnu- \
> >                                 CROSS_COMPILE_ARM32=${CLANG_PATH}/bin/arm-linux-gnueabi- \
> >                                 LD=ld.lld "
> > export BUILD_ARGS="-j${TH_COUNT} ${DEF_ARGS}"
> > 
> > echo -e "${cwarn}kernel workspace dir is => ${KERNEL_DIR}"
> > echo -e "kernel build defonfig is => ${KERNEL_DEFCONFIG}"
> > echo -e "build tmpdir is => ${KERNEL_DIR}/${OUT}"
> > echo -e "clang path is => ${CLANG_PATH}"
> > echo -e "build arch/subarch is => ${ARCH} / ${SUBARCH}${cno}"
> > # 等待10s，查看配置文件信息是否正确，不正确 Ctrl + C 及时取消
> > sleep 10s
> > 
> > echo -e "${cinfo}=============== Make defconfig ===============${cno}"
> > # make defconfig
> > make ${DEF_ARGS} ${KERNEL_DEFCONFIG}
> > # 如果命令没有出错，继续执行，否则退出编译
> > if [[ "0" != "$?" ]]; then
> >         echo -e "${cerror}>>> make defconfig error, build stop!${cno}"
> >         exit 1
> > fi
> > 
> > echo -e "${cinfo}=============== Make Kernel  ===============${cno}"
> > make ${BUILD_ARGS}
> > if [[ "0" != "$?" ]]; then
> >         echo -e "${cerror}>>> build kernel error, build stop!${cno}"
> >         exit 1
> > fi
> > echo -e "${cwarn}>>> build kernel success${cno}"
> > exit 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The compilation passed successfully.
> > Extract the boot.img of MIUI 14.0.3 wirebrush package Unpack it by unpacking tool (https://github.com/xiaoxindada/magiskboot_ndk_on_linux) ![image](https://user-images.githubusercontent.com/100894732/246603968-2fb8f3cb-4149-4efd-aeb9-0b73e4b89dd5.png)
> > Delete the unpacked kernel ![image](https://user-images.githubusercontent.com/100894732/246603979-0ccee865-2934-43e1-8c6f-06c64efcd3ce.png)
> > Replace the kernel with the compiled Image (Image:out/arch/arm64/boot/Image) ![image](https://user-images.githubusercontent.com/100894732/246603990-f42f23b3-9fcd-4e70-827b-8efb9f47b323.png) ![image](https://user-images.githubusercontent.com/100894732/246604002-89705467-9e7e-451c-a06a-c877b7f4dd14.png)
> > Finally, package it back
> > Enter fastboot Refresh process
> > ![image](https://user-images.githubusercontent.com/100894732/246603931-926df72b-d6b0-43eb-84f5-8cca42a09a7d.png)
> > Result bootloop
> > (Directly flashed into the extracted original boot.img, can boot up smoothly)
> 
> this kernel source is based on Android 11, used for building aosp rom

Yes, I have flashed MIUI 12.5.12.0.
Now my phone is on Android 11.
And it's successfully flashed and booted.

But the USB doesn't work, it doesn't charge, it doesn't connect to the PC.
xD

---------------------------------------------------------------------------------
How do I fix it?
Or what logs do you need me to upload?

I'm just an idiot.

**Comment by hamjin** [comment]
> > > Phone Model:Redmi K40 Gaming (Mainland China version) System Version:MIUI 14.0.3 Processor:MTK D1200
> > > Compiler tool:https://github.com/ZyCromerZ/Clang
> > > Here is my compilation script.
> > > ```shell
> > > #!/bin/bash
> > > ###########################
> > > #  a kernel build script
> > > ###########################
> > > 
> > > ##
> > > #  some color setting
> > > ##
> > > cinfo="\x1b[38;2;79;155;250m"
> > > cwarn="\x1b[38;2;255;200;97m"
> > > cerror="\x1b[38;2;240;96;96m"
> > > cno="\x1b[0"
> > > 
> > > 
> > > echo -e "${cinfo}=============== Setup Some Export ===============${cno}"
> > > # 内核工作目录
> > > export KERNEL_DIR=$(pwd)
> > > # 内核 defconfig 文件
> > > export KERNEL_DEFCONFIG=aresin_defconfig
> > > # 编译临时目录，避免污染根目录
> > > export OUT=out
> > > # clang 绝对路径
> > > export CLANG_PATH=/root/k40g/toolchain/zyc-clang
> > > export PATH=${CLANG_PATH}/bin:${PATH}
> > > export CLANG_TRIPLE=aarch64-linux-gnu-
> > > # arch平台，这里时arm64
> > > export ARCH=arm64
> > > export SUBARCH=arm64
> > > # 只使用clang编译需要配置
> > > export LLVM=1
> > > export BUILD_INITRAMFS=1
> > > 
> > > # 编译时线程指定，默认单线程，可以通过参数指定，比如4线程编译
> > > # ./build.sh 4 
> > > TH_COUNT=32
> > > if [[ "" != "$1" ]]; then
> > >         TH_NUM=$1
> > > fi
> > > 
> > > # 编译参数
> > > export DEF_ARGS="O=${OUT} \
> > >                                 CC=clang \
> > >                                 CXX=clang++ \
> > >                                 ARCH=${ARCH} \
> > >                                 CROSS_COMPILE=${CLANG_PATH}/bin/aarch64-linux-gnu- \
> > >                                 CROSS_COMPILE_ARM32=${CLANG_PATH}/bin/arm-linux-gnueabi- \
> > >                                 LD=ld.lld "
> > > export BUILD_ARGS="-j${TH_COUNT} ${DEF_ARGS}"
> > > 
> > > echo -e "${cwarn}kernel workspace dir is => ${KERNEL_DIR}"
> > > echo -e "kernel build defonfig is => ${KERNEL_DEFCONFIG}"
> > > echo -e "build tmpdir is => ${KERNEL_DIR}/${OUT}"
> > > echo -e "clang path is => ${CLANG_PATH}"
> > > echo -e "build arch/subarch is => ${ARCH} / ${SUBARCH}${cno}"
> > > # 等待10s，查看配置文件信息是否正确，不正确 Ctrl + C 及时取消
> > > sleep 10s
> > > 
> > > echo -e "${cinfo}=============== Make defconfig ===============${cno}"
> > > # make defconfig
> > > make ${DEF_ARGS} ${KERNEL_DEFCONFIG}
> > > # 如果命令没有出错，继续执行，否则退出编译
> > > if [[ "0" != "$?" ]]; then
> > >         echo -e "${cerror}>>> make defconfig error, build stop!${cno}"
> > >         exit 1
> > > fi
> > > 
> > > echo -e "${cinfo}=============== Make Kernel  ===============${cno}"
> > > make ${BUILD_ARGS}
> > > if [[ "0" != "$?" ]]; then
> > >         echo -e "${cerror}>>> build kernel error, build stop!${cno}"
> > >         exit 1
> > > fi
> > > echo -e "${cwarn}>>> build kernel success${cno}"
> > > exit 0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The compilation passed successfully.
> > > Extract the boot.img of MIUI 14.0.3 wirebrush package Unpack it by unpacking tool (https://github.com/xiaoxindada/magiskboot_ndk_on_linux) ![image](https://user-images.githubusercontent.com/100894732/246603968-2fb8f3cb-4149-4efd-aeb9-0b73e4b89dd5.png)
> > > Delete the unpacked kernel ![image](https://user-images.githubusercontent.com/100894732/246603979-0ccee865-2934-43e1-8c6f-06c64efcd3ce.png)
> > > Replace the kernel with the compiled Image (Image:out/arch/arm64/boot/Image) ![image](https://user-images.githubusercontent.com/100894732/246603990-f42f23b3-9fcd-4e70-827b-8efb9f47b323.png) ![image](https://user-images.githubusercontent.com/100894732/246604002-89705467-9e7e-451c-a06a-c877b7f4dd14.png)
> > > Finally, package it back
> > > Enter fastboot Refresh process
> > > ![image](https://user-images.githubusercontent.com/100894732/246603931-926df72b-d6b0-43eb-84f5-8cca42a09a7d.png)
> > > Result bootloop
> > > (Directly flashed into the extracted original boot.img, can boot up smoothly)
> > 
> > 
> > this kernel source is based on Android 11, used for building aosp rom
> 
> Yes, I have flashed MIUI 12.5.12.0. Now my phone is on Android 11. And it's successfully flashed and booted.
> 
> But the USB doesn't work, it doesn't charge, it doesn't connect to the PC. xD
> 
> How do I fix it? Or what logs do you need me to upload?
> 
> I'm just an idiot.

Use an old version Clang (<=14) and retry?

**Comment by hamjin** [comment]
> 这个内核代码只适用于A11,或许你应该尝试https://github.com/anotherjin/android_kernel_xiaomi_ares 虽然这个是适用于A12,A13的miui,但可能会有很多问题。 最好的解决方法是降级到A11

Deprecated and you should use branch T in this repo or https://github.com/AbzRaider/kernel_xiaomi_ares/

**Comment by Tkpointz** [comment]
T branch exist here too

> > 这个内核代码只适用于A11,或许你应该尝试https://github.com/anotherjin/android_kernel_xiaomi_ares 虽然这个是适用于A12,A13的miui,但可能会有很多问题。 最好的解决方法是降级到A11
> 
> Deprecated and you should use branch T in this repo or https://github.com/AbzRaider/kernel_xiaomi_ares/

T source is added here too with connectivity drivers check branch T

**Comment by ImKK666** [comment]
Perfect I'm using branch T. No problems ！！！！
